# Generated by Django 5.0.4 on 2024-04-08 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='comapany_id',
            new_name='company_id',
        ),
    ]
